[build]
  publish = "src"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/info"
  to = "/info.html"
  status = 200

[[redirects]]
  from = "/choice-cuts"
  to = "/choice-cuts.html"
  status = 200

[[redirects]]
  from = "/long-copy"
  to = "/long-copy.html"
  status = 200
