[build]
  publish = "src"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/films"
  to = "/films.html"
  status = 200

[[redirects]]
  from = "/choice-cuts"
  to = "/choice-cuts.html"
  status = 200

[[redirects]]
  from = "/long-pour"
  to = "/long-pour.html"
  status = 200

[[redirects]]
  from = "/long-copy"
  to = "/long-pour.html"
  status = 301

[[redirects]]
  from = "/long-copy.html"
  to = "/long-pour.html"
  status = 301

[[redirects]]
  from = "/resume"
  to = "/resume/index.html"
  status = 200

[[redirects]]
  from = "/IMMORTAL"
  to = "/IMMORTAL/index.html"
  status = 200

[[redirects]]
  from = "/project/holiday-plus-one"
  to = "https://meanwhileinjupiter.com/holiday/2025/piece/"
  status = 301
